services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: fms
      POSTGRES_DB: fms
    ports:
      - "5432:5432"
    volumes:
      - fms-db-data:/var/lib/postgresql/data

volumes:
  fms-db-data:
